import pandas as pd
import numpy as np
import logging
import os
import joblib
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, confusion_matrix, roc_curve
)
from sklearn.model_selection import train_test_split # For potential utility, though we do chronological.

# --- Logger Setup ---
logger = logging.getLogger(__name__)
# Assume calling script configures logger. For standalone testing, basicConfig can be used.

# --- Configuration ---
DEFAULT_INPUT_LABELED_M5_CSV = 'eur_usd_m5_labeled_data.csv'
DEFAULT_MODEL_OUTPUT_FILENAME = 'intraday_m5_model_v1.joblib'
LOG_FILE = 'intraday_model_trainer.log' # Specific log file for this script

TARGET_COLUMN = 'up_move_success'
TEST_SET_SIZE = 0.2  # Use 20% of data for testing (most recent)
RANDOM_STATE = 42

# Define the initial feature set to be used for training
# These should be columns already generated by intraday_feature_engineer.py
# and present in the INPUT_LABELED_M5_CSV
FEATURE_COLUMNS_TO_USE = [
    'ema_5',
    'ema_12',
    'rsi_9',
    'atr_14',
    'vwap',
    'ema_trend_score'
    # Consider adding 'volume' or price relative to VWAP (e.g., close - vwap) if not already captured
    # For now, keeping it to the explicitly engineered ones.
]

def load_labeled_data(csv_filepath=DEFAULT_INPUT_LABELED_M5_CSV):
    """Loads M5 data with features and target label."""
    logger.info(f"Attempting to load labeled M5 data from: {csv_filepath}")
    if not os.path.exists(csv_filepath):
        logger.error(f"Labeled M5 data file not found: {csv_filepath}")
        return None

    try:
        df = pd.read_csv(csv_filepath)
        if df.empty:
            logger.warning(f"Labeled M5 data file is empty: {csv_filepath}")
            return pd.DataFrame()

        logger.info(f"Successfully loaded {len(df)} records from {csv_filepath}.")

        if 'timestamp' not in df.columns:
            logger.error("Labeled M5 data CSV must contain a 'timestamp' column.")
            return None
        df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce', utc=True)
        df.dropna(subset=['timestamp'], inplace=True)
        df.set_index('timestamp', inplace=True)
        df.sort_index(inplace=True) # Ensure chronological order

        if TARGET_COLUMN not in df.columns:
            logger.error(f"Target column '{TARGET_COLUMN}' not found in the data.")
            return None

        # Convert target to int, coercing errors (should be 0 or 1 already)
        df[TARGET_COLUMN] = pd.to_numeric(df[TARGET_COLUMN], errors='coerce').astype('Int64') # Use Int64 to allow NaNs

        # Check for required feature columns
        if not all(col in df.columns for col in FEATURE_COLUMNS_TO_USE):
            missing_features = [col for col in FEATURE_COLUMNS_TO_USE if col not in df.columns]
            logger.error(f"Missing required feature columns: {missing_features}")
            return None

        return df
    except Exception as e:
        logger.error(f"Error loading labeled M5 data from {csv_filepath}: {e}", exc_info=True)
        return None

def prepare_data_for_training(df, target_column_name=TARGET_COLUMN, feature_cols=FEATURE_COLUMNS_TO_USE):
    """Prepares X (features) and y (target) for training, handling NaNs."""
    logger.info(f"Preparing data for training. Using target: '{target_column_name}', Features: {feature_cols}")

    if df is None or df.empty:
        logger.error("Input DataFrame is None or empty in prepare_data_for_training.")
        return None, None

    # Select features and target
    X = df[feature_cols].copy()
    y = df[target_column_name].copy()

    # Handle NaNs:
    # 1. NaNs in target column (e.g., from labeling process for trailing rows)
    if y.isnull().any():
        logger.warning(f"Target column '{target_column_name}' contains {y.isnull().sum()} NaNs. These rows will be dropped.")
        X = X[y.notnull()]
        y = y[y.notnull()]
        if y.empty:
            logger.error("Target column became empty after dropping NaNs. Cannot proceed.")
            return None, None

    # 2. NaNs in feature columns (e.g., from indicator calculation for initial rows)
    if X.isnull().any().any(): # .any().any() checks if any NaN exists anywhere in DataFrame X
        logger.warning(f"Feature set X contains NaNs. Dropping rows with any NaNs in selected features.")
        # Get combined index of non-NaN rows for both X and y
        combined_notnull_idx = X.dropna().index.intersection(y.dropna().index)
        X = X.loc[combined_notnull_idx]
        y = y.loc[combined_notnull_idx]

        if X.empty or y.empty:
            logger.error("X or y became empty after dropping NaN rows from features. Cannot proceed.")
            return None, None

    logger.info(f"Data preparation complete. X shape: {X.shape}, y shape: {y.shape}")
    if not X.empty:
        logger.debug(f"Class distribution in y: \n{y.value_counts(normalize=True)}")
    return X, y

def split_data_chronological(X, y, test_size_ratio=TEST_SET_SIZE):
    """Splits data chronologically into training and testing sets."""
    if X is None or y is None or X.empty or y.empty:
        logger.error("Input X or y is None or empty for splitting.")
        return None, None, None, None

    split_index = int(len(X) * (1 - test_size_ratio))
    if split_index == 0 or split_index == len(X):
        logger.error(f"Cannot split data: split_index ({split_index}) is at an extreme. "
                     f"Data length: {len(X)}, test_size_ratio: {test_size_ratio}. "
                     "Ensure enough data for both train and test sets.")
        return None, None, None, None

    X_train = X.iloc[:split_index]
    X_test = X.iloc[split_index:]
    y_train = y.iloc[:split_index]
    y_test = y.iloc[split_index:]

    logger.info(f"Data split chronologically. Train size: {len(X_train)}, Test size: {len(X_test)}")
    return X_train, X_test, y_train, y_test

def train_classification_model(X_train, y_train, model_type='logistic_regression', random_state=RANDOM_STATE):
    """Trains a classification model (Logistic Regression for now)."""
    logger.info(f"Training {model_type} model...")
    if X_train is None or y_train is None or X_train.empty or y_train.empty:
        logger.error("Training data (X_train or y_train) is missing or empty.")
        return None

    if model_type == 'logistic_regression':
        model = LogisticRegression(solver='liblinear', class_weight='balanced', random_state=random_state)
    else:
        logger.error(f"Unsupported model_type: {model_type}")
        return None

    try:
        model.fit(X_train, y_train)
        logger.info(f"{model_type} model training completed.")
        return model
    except Exception as e:
        logger.error(f"Error during model training: {e}", exc_info=True)
        return None

def evaluate_classification_model(model, X_test, y_test):
    """Evaluates the classification model and logs metrics."""
    if model is None or X_test is None or y_test is None or X_test.empty or y_test.empty:
        logger.error("Cannot evaluate: model or test data is missing or empty.")
        return None

    logger.info("Evaluating model on the test set...")
    try:
        y_pred = model.predict(X_test)
        y_pred_proba = model.predict_proba(X_test)[:, 1] # Probability of class 1

        metrics = {
            "accuracy": accuracy_score(y_test, y_pred),
            "precision": precision_score(y_test, y_pred, zero_division=0),
            "recall": recall_score(y_test, y_pred, zero_division=0),
            "f1_score": f1_score(y_test, y_pred, zero_division=0),
            "roc_auc": roc_auc_score(y_test, y_pred_proba),
            "confusion_matrix": confusion_matrix(y_test, y_pred).tolist() # .tolist() for easy logging
        }

        logger.info("Model Evaluation Metrics:")
        for metric_name, value in metrics.items():
            if metric_name == "confusion_matrix":
                logger.info(f"  {metric_name}:")
                for row in value: logger.info(f"    {row}")
            else:
                logger.info(f"  {metric_name}: {value:.4f}")
        return metrics
    except Exception as e:
        logger.error(f"Error during model evaluation: {e}", exc_info=True)
        return None

def save_trained_model(model, filepath=DEFAULT_MODEL_OUTPUT_FILENAME):
    """Saves the trained model to a file using joblib."""
    if model is None:
        logger.error("Model is None, cannot save.")
        return False
    logger.info(f"Saving trained model to: {filepath}")
    try:
        joblib.dump(model, filepath)
        logger.info(f"Model successfully saved to {filepath}")
        return True
    except Exception as e:
        logger.error(f"Error saving model to {filepath}: {e}", exc_info=True)
        return False

def main_train_pipeline():
    logger.info("--- Starting Intraday M5 Model Training Pipeline ---")

    # 1. Load Data
    df = load_labeled_data()
    if df is None or df.empty:
        logger.critical("Failed to load labeled data or data is empty. Exiting pipeline.")
        return

    # 2. Prepare Data for Training
    X, y = prepare_data_for_training(df) # Uses global TARGET_COLUMN and FEATURE_COLUMNS_TO_USE
    if X is None or y is None or X.empty or y.empty:
        logger.critical("Failed to prepare data for training (X or y is empty/None). Exiting pipeline.")
        return

    # 3. Split Data
    X_train, X_test, y_train, y_test = split_data_chronological(X, y)
    if X_train is None or X_test is None or y_train is None or y_test is None: # Check if any are None
        logger.critical("Failed to split data. Exiting pipeline.")
        return
    if X_train.empty or X_test.empty or y_train.empty or y_test.empty: # Check if any are empty
        logger.critical("One or more data splits are empty. Exiting pipeline.")
        return

    # 4. Train Model
    model = train_classification_model(X_train, y_train) # Uses default Logistic Regression
    if model is None:
        logger.critical("Model training failed. Exiting pipeline.")
        return

    # 5. Evaluate Model
    metrics = evaluate_classification_model(model, X_test, y_test)
    if metrics is None:
        logger.warning("Model evaluation failed or produced no metrics. Proceeding to save model anyway.")
        # Depending on policy, might not want to save if evaluation fails.

    # 6. Save Model
    save_trained_model(model)

    logger.info("--- Intraday M5 Model Training Pipeline Finished ---")

if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO,
                        format='%(asctime)s - %(levelname)s - %(name)s - %(filename)s:%(lineno)d - %(message)s',
                        handlers=[logging.StreamHandler()])
    try:
        fh = logging.FileHandler(LOG_FILE)
        fh.setFormatter(logging.Formatter('%(asctime)s - %(levelname)s - %(name)s - %(filename)s:%(lineno)d - %(message)s'))
        logging.getLogger().addHandler(fh)
    except Exception as e:
        logger.error(f"Could not add file handler for {LOG_FILE} in standalone mode: {e}")

    # Create dummy labeled data for testing if main file doesn't exist
    if not os.path.exists(DEFAULT_INPUT_LABELED_M5_CSV):
        logger.info(f"Creating dummy labeled data file: {DEFAULT_INPUT_LABELED_M5_CSV} for testing.")
        num_rows_test = 300 # Enough for train/test split and some NaNs from features
        base_time = datetime.now(timezone.utc) - timedelta(minutes=5*num_rows_test)
        test_data = {
            'timestamp': pd.date_range(start=base_time, periods=num_rows_test, freq='5min', tz='UTC'),
        }
        _df = pd.DataFrame(test_data)
        # Add feature columns (random data for testing)
        for col in FEATURE_COLUMNS_TO_USE:
            _df[col] = np.random.rand(num_rows_test) * 10
        _df[TARGET_COLUMN] = np.random.randint(0, 2, num_rows_test) # Random 0s and 1s

        # Simulate some NaNs at the beginning of features
        for col in FEATURE_COLUMNS_TO_USE:
            _df.loc[_df.index[:15], col] = np.nan

        _df.to_csv(DEFAULT_INPUT_LABELED_M5_CSV, index=False) # load_labeled_data expects timestamp as column

    main_train_pipeline()

    # Clean up dummy file if it was created by this test run
    # (Add a flag or check if it existed before if you want to be more careful)
    # For now, if it's the default name and test created it, remove.
    # if os.path.exists(DEFAULT_INPUT_LABELED_M5_CSV) and 'test_df' in locals(): # A bit fragile check
    #     os.remove(DEFAULT_INPUT_LABELED_M5_CSV)
    #     logger.info(f"Removed dummy labeled data file: {DEFAULT_INPUT_LABELED_M5_CSV}")
    # Better to just log that output was created:
    logger.info(f"Test run finished. Model (if trained) saved to {DEFAULT_MODEL_OUTPUT_FILENAME}.")
    logger.info(f"Input data was {DEFAULT_INPUT_LABELED_M5_CSV}.")
